-- 043_truck_planner_core.sql - Truck Planner owner tables.
--
-- tp_trucks, tp_spots, tp_plans, tp_plan_stops, tp_service_logs, tp_drive_overrides and tp_scout_leads
-- are organization-scoped. tp_drive_legs is the shared 30-day cache of Google legs and has no tenant column.
-- Money is integer cents, fuel prices are thousandths of a dollar, fractions and model inputs are DOUBLE.
-- tp_trucks.overrides_json and the four stored snapshots (tp_plans.result_json, tp_plans.context_json,
-- tp_service_logs.weather_json, tp_service_logs.prediction_json) hold JSON text in MEDIUMTEXT columns,
-- because a JSON column hands some 16- and 17-digit numbers back one unit in the last place off.
-- Idempotent: CREATE TABLE IF NOT EXISTS and INSERT ... ON DUPLICATE KEY UPDATE only. No foreign keys.
-- Splitter rule: statement-ending semicolons at the end of a line, none inside comments.

CREATE TABLE IF NOT EXISTS tp_trucks (
  id                         CHAR(36)      PRIMARY KEY,
  organization_id            CHAR(36)      NOT NULL,
  created_by                 CHAR(36)      NULL,
  name                       VARCHAR(120)  NOT NULL,
  region_id                  VARCHAR(24)   CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'none',
  timezone                   VARCHAR(60)   NOT NULL,
  base_lat                   DOUBLE        NOT NULL,
  base_lng                   DOUBLE        NOT NULL,
  base_address               VARCHAR(255)  NOT NULL DEFAULT '',
  base_state                 VARCHAR(2)    NULL,
  base_county_fips           VARCHAR(5)    CHARACTER SET ascii COLLATE ascii_bin NULL,
  avg_ticket_cents           INT UNSIGNED  NOT NULL,
  capacity_orders_per_hour   DOUBLE        NOT NULL,
  paid_crew                  TINYINT UNSIGNED NOT NULL,
  wage_cents                 INT UNSIGNED  NOT NULL,
  payroll_burden_pct         DOUBLE        NOT NULL,
  food_cost_pct              DOUBLE        NOT NULL,
  packaging_cents            INT UNSIGNED  NOT NULL,
  card_fee_pct               DOUBLE        NOT NULL,
  card_fee_fixed_cents       INT UNSIGNED  NOT NULL,
  card_share                 DOUBLE        NOT NULL,
  tips_include               TINYINT UNSIGNED NOT NULL DEFAULT 0,
  tips_pct                   DOUBLE        NOT NULL,
  mpg                        DOUBLE        NOT NULL,
  fuel_type                  VARCHAR(8)    NOT NULL DEFAULT 'gasoline',
  fuel_price_override_milli  INT UNSIGNED  NULL,
  generator_gal_per_hour     DOUBLE        NOT NULL,
  prep_minutes               SMALLINT UNSIGNED NOT NULL,
  setup_minutes              SMALLINT UNSIGNED NOT NULL,
  teardown_minutes           SMALLINT UNSIGNED NOT NULL,
  closeout_minutes           SMALLINT UNSIGNED NOT NULL,
  fixed_cost_day_cents       INT UNSIGNED  NOT NULL DEFAULT 0,
  fit_breakfast              DOUBLE        NOT NULL,
  fit_lunch                  DOUBLE        NOT NULL,
  fit_dinner                 DOUBLE        NOT NULL,
  fit_late                   DOUBLE        NOT NULL,
  avoid_tolls                TINYINT UNSIGNED NOT NULL DEFAULT 0,
  avoid_highways             TINYINT UNSIGNED NOT NULL DEFAULT 0,
  truck_time_factor          DOUBLE        NOT NULL,
  licence_counties_json      JSON          NOT NULL,
  scout_drive_minutes_limit  SMALLINT UNSIGNED NOT NULL,
  overrides_json             MEDIUMTEXT    NOT NULL,
  overrides_seeds_rev        INT UNSIGNED  NOT NULL DEFAULT 1,
  created_at                 DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at                 DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_tptr_org (organization_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tp_spots (
  id                 CHAR(36)      PRIMARY KEY,
  organization_id    CHAR(36)      NOT NULL,
  truck_id           CHAR(36)      NOT NULL,
  created_by         CHAR(36)      NULL,
  name               VARCHAR(120)  NOT NULL,
  lat                DOUBLE        NOT NULL,
  lng                DOUBLE        NOT NULL,
  address            VARCHAR(255)  NOT NULL DEFAULT '',
  county_fips        VARCHAR(5)    CHARACTER SET ascii COLLATE ascii_bin NULL,
  notes              TEXT          NULL,
  visibility         VARCHAR(10)   NOT NULL DEFAULT 'normal',
  host_segment       VARCHAR(16)   CHARACTER SET ascii COLLATE ascii_bin NULL,
  host_size          DOUBLE        NULL,
  host_size_source   VARCHAR(8)    NULL,
  host_only_food     TINYINT UNSIGNED NOT NULL DEFAULT 0,
  host_place_type    VARCHAR(24)   CHARACTER SET ascii COLLATE ascii_bin NULL,
  host_name          VARCHAR(160)  NULL,
  host_contact       VARCHAR(160)  NULL,
  host_phone         VARCHAR(40)   NULL,
  host_website       VARCHAR(255)  NULL,
  place_key          VARCHAR(20)   CHARACTER SET ascii COLLATE ascii_bin NULL,
  host_point_id      VARCHAR(24)   CHARACTER SET ascii COLLATE ascii_bin NULL,
  google_place_id    VARCHAR(255)  NULL,
  fee_flat_cents     INT UNSIGNED  NOT NULL DEFAULT 0,
  fee_pct            DOUBLE        NOT NULL DEFAULT 0,
  fee_min_cents      INT UNSIGNED  NOT NULL DEFAULT 0,
  allowed_json       JSON          NULL,
  vectors_bin        VARBINARY(1200) NULL,
  vec_in_region      TINYINT UNSIGNED NOT NULL DEFAULT 0,
  vec_points_used    INT UNSIGNED  NOT NULL DEFAULT 0,
  vec_excluded       DOUBLE        NOT NULL DEFAULT 0,
  vec_region_id      VARCHAR(24)   CHARACTER SET ascii COLLATE ascii_bin NULL,
  vec_dataset        VARCHAR(48)   CHARACTER SET ascii COLLATE ascii_bin NULL,
  vec_seeds_rev      INT UNSIGNED  NULL,
  vec_at             DATETIME      NULL,
  archived_at        DATETIME      NULL,
  created_at         DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_tpsp_truck (organization_id, truck_id, archived_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tp_plans (
  id                 CHAR(36)      PRIMARY KEY,
  organization_id    CHAR(36)      NOT NULL,
  truck_id           CHAR(36)      NOT NULL,
  created_by         CHAR(36)      NULL,
  service_date       DATE          NOT NULL,
  name               VARCHAR(120)  NOT NULL DEFAULT '',
  treat_as           VARCHAR(8)    NULL,
  notes              TEXT          NULL,
  plan_state         VARCHAR(12)   NOT NULL DEFAULT 'draft',
  result_json        MEDIUMTEXT    NULL,
  context_json       MEDIUMTEXT    NULL,
  result_has_google  TINYINT UNSIGNED NOT NULL DEFAULT 0,
  evaluated_at       DATETIME      NULL,
  model_version      VARCHAR(24)   NULL,
  seeds_revision     INT UNSIGNED  NULL,
  dataset_version    VARCHAR(48)   CHARACTER SET ascii COLLATE ascii_bin NULL,
  created_at         DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_tppl_truck_date (truck_id, service_date),
  KEY idx_tppl_org_date (organization_id, service_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tp_plan_stops (
  id                   CHAR(36)     PRIMARY KEY,
  organization_id      CHAR(36)     NOT NULL,
  plan_id              CHAR(36)     NOT NULL,
  seq                  SMALLINT UNSIGNED NOT NULL,
  stop_kind            VARCHAR(10)  NOT NULL,
  spot_id              CHAR(36)     NULL,
  label                VARCHAR(120) NOT NULL DEFAULT '',
  lat                  DOUBLE       NULL,
  lng                  DOUBLE       NULL,
  address              VARCHAR(255) NOT NULL DEFAULT '',
  open_minute          SMALLINT UNSIGNED NOT NULL,
  close_minute         SMALLINT UNSIGNED NOT NULL,
  gap_before_unpaid    TINYINT UNSIGNED NOT NULL DEFAULT 0,
  setup_minutes        SMALLINT UNSIGNED NULL,
  teardown_minutes     SMALLINT UNSIGNED NULL,
  fee_flat_cents       INT UNSIGNED NOT NULL DEFAULT 0,
  fee_pct              DOUBLE       NOT NULL DEFAULT 0,
  fee_min_cents        INT UNSIGNED NOT NULL DEFAULT 0,
  ev_attendance        DOUBLE       NULL,
  ev_vendor_count      SMALLINT UNSIGNED NULL,
  ev_type              VARCHAR(16)  NULL,
  cat_headcount        DOUBLE       NULL,
  cat_price_head_cents INT UNSIGNED NULL,
  cat_guarantee_cents  INT UNSIGNED NULL,
  cat_food_cost_cents  INT UNSIGNED NULL,
  created_at           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_tpps_plan_seq (plan_id, seq),
  KEY idx_tpps_org (organization_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tp_service_logs (
  id                 CHAR(36)     PRIMARY KEY,
  organization_id    CHAR(36)     NOT NULL,
  truck_id           CHAR(36)     NOT NULL,
  created_by         CHAR(36)     NULL,
  log_kind           VARCHAR(10)  NOT NULL DEFAULT 'spot',
  spot_id            CHAR(36)     NULL,
  plan_id            CHAR(36)     NULL,
  plan_stop_id       CHAR(36)     NULL,
  service_date       DATE         NOT NULL,
  open_minute        SMALLINT UNSIGNED NOT NULL,
  close_minute       SMALLINT UNSIGNED NOT NULL,
  actual_orders      INT UNSIGNED NOT NULL,
  sales_cents        INT UNSIGNED NULL,
  sold_out           TINYINT UNSIGNED NOT NULL DEFAULT 0,
  notes              TEXT         NULL,
  src                VARCHAR(16)  CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'manual',
  external_key       VARCHAR(120) CHARACTER SET ascii COLLATE ascii_bin NULL,
  treat_as           VARCHAR(8)   NULL,
  weather_json       MEDIUMTEXT   NULL,
  predicted_raw      DOUBLE       NULL,
  pred_raw_basis     CHAR(40)     CHARACTER SET ascii COLLATE ascii_bin NULL,
  predicted          DOUBLE       NULL,
  pred_low           DOUBLE       NULL,
  pred_high          DOUBLE       NULL,
  pred_confidence    VARCHAR(12)  NULL,
  pred_basis         VARCHAR(8)   NULL,
  prediction_json    MEDIUMTEXT   NULL,
  pred_model_version VARCHAR(24)  NULL,
  pred_seeds_rev     INT UNSIGNED NULL,
  pred_dataset       VARCHAR(48)  CHARACTER SET ascii COLLATE ascii_bin NULL,
  created_at         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_tpsv_ext (organization_id, src, external_key),
  KEY idx_tpsv_truck_date (organization_id, truck_id, service_date),
  KEY idx_tpsv_spot (organization_id, spot_id, service_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Shared cache of Google legs. Rows older than 30 days are never served. They are deleted by the routing
-- service at the end of each call and by the daily purge script.
-- A straight-line estimate is never written here.
CREATE TABLE IF NOT EXISTS tp_drive_legs (
  o_lat_e4      INT          NOT NULL,
  o_lng_e4      INT          NOT NULL,
  d_lat_e4      INT          NOT NULL,
  d_lng_e4      INT          NOT NULL,
  route_key     VARCHAR(8)   CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  src           VARCHAR(24)  CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  route_found   TINYINT UNSIGNED NOT NULL DEFAULT 1,
  duration_s    INT UNSIGNED NOT NULL DEFAULT 0,
  distance_m    INT UNSIGNED NOT NULL DEFAULT 0,
  toll_state    TINYINT UNSIGNED NOT NULL DEFAULT 0,
  toll_cents    INT UNSIGNED NULL,
  fetched_at    DATETIME     NOT NULL,
  PRIMARY KEY (o_lat_e4, o_lng_e4, d_lat_e4, d_lng_e4, route_key),
  KEY idx_tpdl_fetched (fetched_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS tp_drive_overrides (
  id               CHAR(36)     PRIMARY KEY,
  organization_id  CHAR(36)     NOT NULL,
  truck_id         CHAR(36)     NOT NULL,
  o_lat_e4         INT          NOT NULL,
  o_lng_e4         INT          NOT NULL,
  d_lat_e4         INT          NOT NULL,
  d_lng_e4         INT          NOT NULL,
  override_minutes SMALLINT UNSIGNED NULL,
  toll_cents       INT UNSIGNED NULL,
  note             VARCHAR(160) NOT NULL DEFAULT '',
  created_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_tpdo_leg (truck_id, o_lat_e4, o_lng_e4, d_lat_e4, d_lng_e4),
  KEY idx_tpdo_org (organization_id, truck_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Of a contact lookup only Google's id of the place is kept, with the outcome of the match and its time.
-- Name, address, phone, website and Maps link of a lookup are Google Places content and are stored nowhere.
CREATE TABLE IF NOT EXISTS tp_scout_leads (
  id               CHAR(36)     PRIMARY KEY,
  organization_id  CHAR(36)     NOT NULL,
  truck_id         CHAR(36)     NOT NULL,
  region_id        VARCHAR(24)  CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  place_key        VARCHAR(20)  CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  place_name       VARCHAR(160) NULL,
  place_type       VARCHAR(24)  CHARACTER SET ascii COLLATE ascii_bin NULL,
  lat              DOUBLE       NULL,
  lng              DOUBLE       NULL,
  lead_state       VARCHAR(12)  NOT NULL DEFAULT 'new',
  notes            TEXT         NULL,
  spot_id          CHAR(36)     NULL,
  google_place_id  VARCHAR(255) NULL,
  g_lookup_state   VARCHAR(12)  NULL,
  g_fetched_at     DATETIME     NULL,
  created_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_tpsc_place (truck_id, region_id, place_key),
  KEY idx_tpsc_org (organization_id, truck_id, lead_state)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Shared token buckets (table from migration 031). Tokens are matrix elements for the first, calls for the second.
INSERT INTO places_rate_buckets (bucket, capacity, fill_rate_per_sec, tokens_available, last_refill_at)
VALUES
  ('tp_routes_elements', 1250, 40.000, 1250, CURRENT_TIMESTAMP(3)),
  ('tp_places_lookup',      5,  0.500,    5, CURRENT_TIMESTAMP(3))
ON DUPLICATE KEY UPDATE bucket = bucket;
